
import React from 'react';
import { motion } from 'framer-motion';
import { Lightbulb, Sparkles, InfoCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

interface InsightHeaderProps {
  title: string;
  description: string;
  showHelp?: boolean;
}

const InsightHeader: React.FC<InsightHeaderProps> = ({ title, description, showHelp = true }) => {
  const { toast } = useToast();

  const handleShowHelp = () => {
    toast({
      title: "AI Insights",
      description: "These are personalized insights generated by our AI system based on your activity and system events."
    });
  };

  return (
    <div className="flex items-center justify-between mb-6 relative">
      <div className="flex items-center">
        <div className="relative">
          <Lightbulb className="h-6 w-6 text-yellow-400" />
          <motion.div
            className="absolute inset-0 text-yellow-400"
            animate={{
              scale: [1, 1.5, 1],
              opacity: [0.5, 0, 0.5],
            }}
            transition={{
              duration: 2,
              repeat: Infinity,
              ease: "linear"
            }}
          >
            <Lightbulb className="h-6 w-6" />
          </motion.div>
        </div>
        <div className="ml-3">
          <h3 className="text-xl font-bold bg-gradient-to-r from-yellow-200 to-yellow-400 bg-clip-text text-transparent">
            {title}
          </h3>
          <p className="text-xs text-flow-foreground/60 mt-0.5">
            {description}
          </p>
        </div>
      </div>
      
      {showHelp && (
        <motion.div 
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <Button 
            variant="ghost" 
            size="sm"
            className="text-xs text-flow-foreground/70 hover:text-flow-accent"
            onClick={handleShowHelp}
          >
            <Sparkles className="h-3.5 w-3.5 mr-1.5 text-yellow-400" />
            How this works
          </Button>
        </motion.div>
      )}
    </div>
  );
};

export default InsightHeader;
