
import React from 'react';
import { GlassMorphism } from '@/components/ui/GlassMorphism';
import { 
  Lightbulb, 
  Sparkles, 
  ArrowUpRight, 
  BarChart3, 
  Users, 
  Bell,
  ChevronRight
} from 'lucide-react';
import { Button } from '../ui/button';
import { Link } from 'react-router-dom';
import { useToast } from '@/hooks/use-toast';

const AIInsights: React.FC = () => {
  const { toast } = useToast();
  
  // Mock data for AI insights
  const insights = [
    {
      id: 1,
      type: 'performance',
      title: 'Traffic spike detected',
      description: 'Your website traffic increased by 27% over the last 24 hours',
      icon: BarChart3,
      action: '/analytics',
      actionText: 'View Analytics'
    },
    {
      id: 2,
      type: 'opportunity',
      title: 'Agent collaboration potential',
      description: 'Analysis suggests pairing writing and research agents would improve content quality',
      icon: Users,
      action: '/agents',
      actionText: 'View Agent Pairings'
    },
    {
      id: 3,
      type: 'notification',
      title: 'System update scheduled',
      description: 'AI model updates planned for tonight at 2:00 AM',
      icon: Bell,
      action: '#',
      actionText: 'View Details',
      onClick: () => toast({
        title: "System Update Details",
        description: "New AI models will be deployed tonight. No downtime expected.",
      })
    }
  ];
  
  const handleInsightAction = (insight: typeof insights[0]) => {
    if (insight.onClick) {
      insight.onClick();
    }
  };

  return (
    <GlassMorphism className="p-6 rounded-xl bg-flow-background/20 backdrop-blur-lg border-flow-accent/20 h-full">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <Lightbulb className="h-5 w-5 mr-2 text-yellow-400" />
          <h3 className="text-lg font-medium">AI Insights</h3>
        </div>
        <Button 
          variant="ghost" 
          size="sm"
          className="text-xs text-flow-foreground/70 hover:text-flow-accent"
          onClick={() => toast({
            title: "AI Insights",
            description: "These are personalized insights generated by our AI system based on your activity and system events."
          })}
        >
          <Sparkles className="h-3.5 w-3.5 mr-1.5 text-yellow-400" />
          How this works
        </Button>
      </div>
      
      <div className="space-y-3 mb-4">
        {insights.map(insight => (
          <div 
            key={insight.id} 
            className="bg-flow-card/30 border border-flow-border/10 rounded-lg p-3 hover:bg-flow-card/40 transition-all cursor-pointer group"
            onClick={() => handleInsightAction(insight)}
          >
            <div className="flex items-start gap-3">
              <div className={`
                p-2 rounded-full 
                ${insight.type === 'performance' ? 'bg-blue-500/20 text-blue-400' : 
                 insight.type === 'opportunity' ? 'bg-green-500/20 text-green-400' : 
                 'bg-yellow-500/20 text-yellow-400'}
              `}>
                <insight.icon className="h-4 w-4" />
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="text-sm font-medium group-hover:text-flow-accent truncate">{insight.title}</h4>
                <p className="text-xs text-flow-foreground/70 mt-0.5">{insight.description}</p>
              </div>
              {insight.action && (
                insight.action.startsWith('/') ? (
                  <Link to={insight.action} className="shrink-0">
                    <Button 
                      variant="ghost" 
                      size="sm" 
                      className="text-[10px] h-7 px-2 text-flow-foreground/70 hover:text-flow-accent group-hover:border-flow-accent/30"
                    >
                      {insight.actionText}
                      <ArrowUpRight className="h-3 w-3 ml-1" />
                    </Button>
                  </Link>
                ) : (
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="text-[10px] h-7 px-2 text-flow-foreground/70 hover:text-flow-accent group-hover:border-flow-accent/30 shrink-0"
                  >
                    {insight.actionText}
                    <ArrowUpRight className="h-3 w-3 ml-1" />
                  </Button>
                )
              )}
            </div>
          </div>
        ))}
      </div>
      
      <div className="pt-2 border-t border-flow-border/10">
        <div className="flex items-center justify-between">
          <span className="text-xs text-flow-foreground/60">Insights based on system activity and user behavior</span>
          <Button 
            variant="ghost" 
            size="sm" 
            className="text-xs p-0 h-7 text-flow-foreground/70 hover:text-flow-accent flex items-center"
          >
            View all insights
            <ChevronRight className="h-3 w-3 ml-0.5" />
          </Button>
        </div>
      </div>
    </GlassMorphism>
  );
};

export default AIInsights;
